name: Build

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "* * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name : run check
        run: ./pr-approve
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
