name: "Close stale issues"
on:
  schedule:
    - cron: "* * * * *"

jobs:
   check:
     runs-on: ubuntu-latest
     steps:
       - name : run check
         run: echo "Hello, world!"
         env:
           GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
